### ISSUE TITLE
Lifesim.pot uses file extension that is already taken by another, major program

### ISSUE THREAD

**Issue by WinFan3672** [fungamer2-2/Life-Simulator1#19]
### **Describe the bug**
The POT file extension is used by Microsoft PowerPoint, as an Office 1997-2003 template.

### **Steps to reproduce**
Get PowerPoint.
Notice that lifesim.pot appears with a PowerPoint icon. 
Try to open it and it cannot read it.

### **Expected behavior**
The file extension for the localisation file should not be taken by any major program. I would recommend changing the .pot to something else.

### Recommended Fix
Change the .pot to something else to avoid confusion.

**Comment by RizkiePratama** [comment]
I Don't think this will be a problem. Considering the [pygettext.py](pygettext.py) is using the [GNU xgettext](https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html#xgettext-Invocation) Standart which it required to be a PO or POT files to begin with.

Changing it to other Extension name might cause other problem down the road if the project it self still using `xgettext`.

**Comment by fungamer2-2** [comment]
I'm not quite sure this would be a problem.

**Comment by fungamer2-2** [comment]
I'll just close this as I don't think this would be a problem down the line, since it is the standard to use `pot` files for localization.
