### ISSUE TITLE
Traits Idea

### ISSUE THREAD

**Issue by fungamer2-2** [fungamer2-2/Life-Simulator1#20]
### **Is your feature request related to a problem? Please describe.**
I'm thinking about adding traits to the game. Some positive, some negative, but they should all affect gameplay in different ways. Although this isn't in BitLife, I'm considering adding it to this game.

### **Describe the solution you'd like**
There should be different traits, some positive, some negative. They should be randomized when choosing "Random Life", and should be selectable when choosing "Custom Life". Also, two opposite traits should not be possible to receive at the same time.

I'm trying to come up with as many as I can. Please suggest traits in the comments and I may add them to this list.

Positive Traits:
- Nerd: Makes it easier to increase smarts by doing activities
- Cheerful: Makes it easier to increase happiness

Negative Traits:
- Grumpy: Harder to get into a good mood, harder to stay in a good mood

Mixed Traits (both positive and negative elements)
- Moody: Happiness changes more, and the changes in happiness (either up or down) are more intense

### **Describe alternatives you've considered**
None

**Comment by Iqrar99** [comment]
If you want to have many traits in this project. I suggest you check this [wiki](https://sims.fandom.com/wiki/Trait_(The_Sims_4)) from The Sims 4 game.

**Comment by MrTanoshii** [comment]
Hope these can provide inspiration

https://eu4.paradoxwikis.com/Personalities

https://www.dwarffortresswiki.org/index.php/DF2014:Personality_trait

**Comment by Solumbra** [comment]
it would be good if you could learn traits by doing something, or select traits for your child/ren (for nature vs nurture).
i.e. you can be born a jock and die a nerd depending on how you go through life.

similar to bit life's sporting, acting, music strengths that make it easier to join the cheerleading / gymnastics / athletics school activities, or to learn acting or an instrument.
which, in turn make it easier to get a job as an athlete, actor, musician.

maybe doing lots of homework each year in school helps to gain the nerd trait > helps to get work in STEM careers / skip some uni
or lots of bullying in school makes it harder to get work that isn't crime, but makes crime work easier. maybe co-workers hate you and do what they can to get you fired (set you up and then report you to HR)

- Jock trait
- Actor
- Musical
- Bully
- Natural born leader

**Comment by fungamer2-2** [comment]
> it would be good if you could learn traits by doing something, or select traits for your child/ren (for nature vs nurture). i.e. you can be born a jock and die a nerd depending on how you go through life.
> 
> similar to bit life's sporting, acting, music strengths that make it easier to join the cheerleading / gymnastics / athletics school activities, or to learn acting or an instrument. which, in turn make it easier to get a job as an athlete, actor, musician.
> 
> maybe doing lots of homework each year in school helps to gain the nerd trait > helps to get work in STEM careers / skip some uni or lots of bullying in school makes it harder to get work that isn't crime, but makes crime work easier. maybe co-workers hate you and do what they can to get you fired (set you up and then report you to HR)
> 
> * Jock trait (sports and fitness, gets more from runs/gym/martial arts + sports careers)
> * Actor (learn acting easily, gets happy easier but also gets sad easier (happy/sad drama face) + acting careers)
> * Musical (learn music/singing easier, people like you a little more, + musical jobs)
> * Bully (better at winning fights, people dislike you more, harder to keep a job, easier crime life & prison escape)
> * Natural born leader (quickly become leader of school activities/cliques, make your own clique, people are drawn to you & like you more, faster job promotion & raises

Sounds like a good idea
For now, I'll be implementing being able to learn the "Nerd" trait and then eventually I'll be able to add other learnable traits

**Comment by Solumbra** [comment]
> Note that when learning a trait, conflicting traits are removed first before actually learning the trait
> 
> For example, if you wanted to learn Fast Worker while having the Slow Worker trait, you'd first have to lose Slow Worker before you could get Fast Worker.

That makes sense for conflicting traits to have a -1, 0, +1 scale

**Comment by fungamer2-2** [comment]
Next, I'm going to add a trait called Book Lover (you gain more happiness when going to the library) which has a small chance of being learned when visiting the library
