### ISSUE TITLE
A contributing.md file

### ISSUE THREAD

**Issue by YashM246** [fungamer2-2/Life-Simulator1#21]
I visited your repo and saw that you do not have a contributing.md file yet. A contributing.md file lets new people understand how to fork the repo and create pull/merge requests,

**Comment by YashM246** [comment]
If possible, I would like this assigned to me under the Hacktober label

**Comment by YashM246** [comment]
@fungamer2-2 could you assign this to me as well? I'll start working on a contributing.md file right away.

**Comment by fungamer2-2** [comment]
#22 has added the file.
