### ISSUE TITLE
French translation 

### ISSUE THREAD

**Issue by b5i** [fungamer2-2/Life-Simulator1#32]
Hello, I’d work on the French translation, could you assign it to me?

**Comment by b5i** [comment]
There is a .mo file that I can't open, so I modify only the .po file?

**Comment by fungamer2-2** [comment]
> There is a .mo file that I can't open, so I modify only the .po file?

You're supposed to fill in the translations from `lifesim.pot`, then save it to a file called `lifesim.po`
