### ISSUE TITLE
Choosing a number other than the 3/4 available ones in the main screen permanently breaks the game

### ISSUE THREAD

**Issue by WinFan3672** [fungamer2-2/Life-Simulator1#5]
Example:
Your name: Ozzie Powers
Gender: Male
Money: $0
Happiness: [||||||||||||||||         ] 65%
Health:    [|||||||||||||||||||||||| ] 96%
Smarts:    [||||||||||               ] 38%
Looks:     [||||||||||||             ] 48%

1. Age
2. Relationships
3. Activities
0 [My choice]

After pressing enter, you enter a broken stage in which all you can do is press ENTER to do nothing, or CTRL+C to end the program.

**Comment by SKR301** [comment]
For me it just accepts the correct response and just ignores the incorrect ones. Doesn't break the game whatsoever!
